name: alhamd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  intl: ^0.20.2
  file_picker: ^10.3.7
  syncfusion_flutter_pdfviewer: ^30.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0   # لازم يكون هنا وليس داخل flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/alhamdsplash.png
    - assets/lang/en.json
    - assets/lang/ar.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/alhamdsplash.png"
